/* =============================================================================
 * DELIVERY DATA TYPES AND SAMPLE DATA
 * ============================================================================= */

export interface DeliveryData {
    id: string;
    // Section A
    admissionDate: string;
    noOfChildren: string;
    deliveryType: string;
    csInstrumentalIndication: string;
    admissionTime: string;
    tears: string[];
    ebl: string;
    episiotomy: string;
    suture: string;
    motherCondition: string;
    otherwiseReason: string;
    motherConditionRemarks: string;
    babyConditionRemarks: string;
    deliveryComments: string;
    deliveredBy: string;
    branch: string;
    // Section B
    deliveryDate: string;
    babyCondition: string;
    babyOtherwiseReason: string;
    gender: string;
    deliveryTime: string;
    babyWeight: string;
    apgarAt1Min: string;
    apgarAt5Min: string;
    // Section C
    dischargeDate: string;
    dischargeTime: string;
    diagnosis: string;
    complicationsFound: string;
    proceduresPerformed: string;
    selectedLabTests: string[];
    selectedScans: string[];
    otherInvestigations: string;
    medicationsPrescribed: string;
    dischargeConditionsInstructions: string;
    conditionAtDischarge: string;
    patientDisposition: string;
    dischargedBy: string;
    followUp: string;
}

export const SAMPLE_DELIVERIES: DeliveryData[] = [
    { id: 'DEL-001', admissionDate: '2024-12-20', noOfChildren: 'Single', deliveryType: 'Normal', csInstrumentalIndication: '', admissionTime: '08:30', tears: ['1st', '2nd'], ebl: '250', episiotomy: 'Yes', suture: 'Vicryl', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Patient stable', babyConditionRemarks: 'Healthy newborn', deliveryComments: 'Smooth delivery', deliveredBy: 'Dr. Sharma', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-20', babyCondition: 'Healthy', babyOtherwiseReason: '', gender: 'Male', deliveryTime: '08:45', babyWeight: '3.2', apgarAt1Min: '8', apgarAt5Min: '9', dischargeDate: '2024-12-22', dischargeTime: '10:00', diagnosis: 'Normal vaginal delivery', complicationsFound: 'None', proceduresPerformed: 'Episiotomy repair', selectedLabTests: ['Hb', 'PPBS', 'HIV'], selectedScans: ['USG dating info'], otherInvestigations: '', medicationsPrescribed: 'Iron supplements', dischargeConditionsInstructions: 'Rest, follow-up in 2 weeks', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Sharma', followUp: '2 weeks' },
    { id: 'DEL-002', admissionDate: '2024-12-19', noOfChildren: 'Twin', deliveryType: 'C-Section', csInstrumentalIndication: 'Fetal distress', admissionTime: '14:15', tears: [], ebl: '500', episiotomy: 'No', suture: 'Vicryl', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Recovery good', babyConditionRemarks: 'Both healthy', deliveryComments: 'Planned CS', deliveredBy: 'Dr. Rao', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-19', babyCondition: 'Healthy', babyOtherwiseReason: '', gender: 'Female', deliveryTime: '14:45', babyWeight: '2.8', apgarAt1Min: '7', apgarAt5Min: '9', dischargeDate: '2024-12-23', dischargeTime: '11:00', diagnosis: 'Twin delivery via CS', complicationsFound: 'None', proceduresPerformed: 'Cesarean section', selectedLabTests: ['Hb', 'PCV'], selectedScans: ['USG growth info'], otherInvestigations: '', medicationsPrescribed: 'Antibiotics', dischargeConditionsInstructions: 'Wound care, follow-up', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Rao', followUp: '1 week' },
    { id: 'DEL-003', admissionDate: '2024-12-18', noOfChildren: 'Single', deliveryType: 'Normal', csInstrumentalIndication: '', admissionTime: '22:45', tears: ['1st'], ebl: '200', episiotomy: 'No', suture: 'Catgut', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Good', babyConditionRemarks: 'Healthy', deliveryComments: 'Quick delivery', deliveredBy: 'Dr. Kumar', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-18', babyCondition: 'Healthy', babyOtherwiseReason: '', gender: 'Female', deliveryTime: '23:15', babyWeight: '3.5', apgarAt1Min: '9', apgarAt5Min: '10', dischargeDate: '2024-12-20', dischargeTime: '14:00', diagnosis: 'Normal delivery', complicationsFound: 'None', proceduresPerformed: 'None', selectedLabTests: ['Hb'], selectedScans: ['USG dating info'], otherInvestigations: '', medicationsPrescribed: 'Iron', dischargeConditionsInstructions: 'Rest', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Kumar', followUp: '2 weeks' },
    { id: 'DEL-004', admissionDate: '2024-12-17', noOfChildren: 'Single', deliveryType: 'Vacuum', csInstrumentalIndication: 'Prolonged labor', admissionTime: '06:00', tears: ['2nd', '3A'], ebl: '350', episiotomy: 'Yes', suture: 'Vicryl', motherCondition: 'Otherwise', otherwiseReason: 'Transfer to ICU', motherConditionRemarks: 'Monitored', babyConditionRemarks: 'NICU care', deliveryComments: 'Assisted delivery', deliveredBy: 'Dr. Patel', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-17', babyCondition: 'NICU Care', babyOtherwiseReason: 'Transfer to NICU', gender: 'Male', deliveryTime: '07:00', babyWeight: '3.1', apgarAt1Min: '5', apgarAt5Min: '7', dischargeDate: '2024-12-24', dischargeTime: '10:00', diagnosis: 'Instrumental delivery', complicationsFound: 'PPH', proceduresPerformed: 'Vacuum extraction', selectedLabTests: ['Hb', 'APTT', 'PT'], selectedScans: ['USG anomaly info'], otherInvestigations: 'Blood transfusion', medicationsPrescribed: 'Multiple', dischargeConditionsInstructions: 'Close monitoring', conditionAtDischarge: 'Improved', patientDisposition: 'Home', dischargedBy: 'Dr. Patel', followUp: '3 days' },
    { id: 'DEL-005', admissionDate: '2024-12-16', noOfChildren: 'Single', deliveryType: 'Normal', csInstrumentalIndication: '', admissionTime: '11:20', tears: [], ebl: '180', episiotomy: 'No', suture: '', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Excellent', babyConditionRemarks: 'Healthy', deliveryComments: 'Smooth', deliveredBy: 'Dr. Singh', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-16', babyCondition: 'Healthy', babyOtherwiseReason: '', gender: 'Female', deliveryTime: '12:00', babyWeight: '2.9', apgarAt1Min: '8', apgarAt5Min: '9', dischargeDate: '2024-12-18', dischargeTime: '09:00', diagnosis: 'Normal delivery', complicationsFound: 'None', proceduresPerformed: 'None', selectedLabTests: ['Hb', 'RBS'], selectedScans: ['USG dating info'], otherInvestigations: '', medicationsPrescribed: 'Vitamins', dischargeConditionsInstructions: 'Normal diet', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Singh', followUp: '2 weeks' },
    { id: 'DEL-006', admissionDate: '2024-12-15', noOfChildren: 'Single', deliveryType: 'Forceps', csInstrumentalIndication: 'Maternal exhaustion', admissionTime: '16:50', tears: ['2nd'], ebl: '300', episiotomy: 'Yes', suture: 'Vicryl', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Recovered well', babyConditionRemarks: 'Healthy', deliveryComments: 'Forceps assisted', deliveredBy: 'Dr. Gupta', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-15', babyCondition: 'Stable', babyOtherwiseReason: '', gender: 'Male', deliveryTime: '17:30', babyWeight: '3.4', apgarAt1Min: '7', apgarAt5Min: '9', dischargeDate: '2024-12-18', dischargeTime: '15:00', diagnosis: 'Forceps delivery', complicationsFound: 'Minor tear', proceduresPerformed: 'Forceps', selectedLabTests: ['Hb', 'VDRL'], selectedScans: ['USG growth info'], otherInvestigations: '', medicationsPrescribed: 'Pain relief', dischargeConditionsInstructions: 'Perineal care', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Gupta', followUp: '1 week' },
    { id: 'DEL-007', admissionDate: '2024-12-14', noOfChildren: 'Triplets', deliveryType: 'C-Section', csInstrumentalIndication: 'Multiple pregnancy', admissionTime: '03:30', tears: [], ebl: '800', episiotomy: 'No', suture: 'Vicryl', motherCondition: 'Otherwise', otherwiseReason: 'Transfer to ICU', motherConditionRemarks: 'ICU monitoring', babyConditionRemarks: 'All in NICU', deliveryComments: 'High-risk delivery', deliveredBy: 'Dr. Reddy', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-14', babyCondition: 'Critical', babyOtherwiseReason: 'Transfer to NICU', gender: 'Male', deliveryTime: '04:15', babyWeight: '2.2', apgarAt1Min: '4', apgarAt5Min: '6', dischargeDate: '2024-12-28', dischargeTime: '11:00', diagnosis: 'Triplet CS delivery', complicationsFound: 'Preterm, PPH', proceduresPerformed: 'Emergency CS', selectedLabTests: ['Hb', 'APTT', 'PT', 'HIV'], selectedScans: ['USG anomaly info', 'USG growth info'], otherInvestigations: 'Multiple', medicationsPrescribed: 'Extensive', dischargeConditionsInstructions: 'NICU follow-up', conditionAtDischarge: 'Stable', patientDisposition: 'Home with NICU visits', dischargedBy: 'Dr. Reddy', followUp: 'Daily NICU' },
    { id: 'DEL-008', admissionDate: '2024-12-13', noOfChildren: 'Single', deliveryType: 'Normal', csInstrumentalIndication: '', admissionTime: '19:10', tears: ['1st'], ebl: '220', episiotomy: 'No', suture: 'Catgut', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Good recovery', babyConditionRemarks: 'Healthy', deliveryComments: 'Normal', deliveredBy: 'Dr. Menon', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-13', babyCondition: 'Healthy', babyOtherwiseReason: '', gender: 'Female', deliveryTime: '20:00', babyWeight: '3.0', apgarAt1Min: '8', apgarAt5Min: '9', dischargeDate: '2024-12-15', dischargeTime: '10:00', diagnosis: 'Normal delivery', complicationsFound: 'None', proceduresPerformed: 'None', selectedLabTests: ['Hb'], selectedScans: ['USG dating info'], otherInvestigations: '', medicationsPrescribed: 'Iron', dischargeConditionsInstructions: 'Rest', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Menon', followUp: '2 weeks' },
    { id: 'DEL-009', admissionDate: '2024-12-12', noOfChildren: 'Twin', deliveryType: 'Normal', csInstrumentalIndication: '', admissionTime: '09:45', tears: ['1st', '2nd'], ebl: '350', episiotomy: 'Yes', suture: 'Vicryl', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Good', babyConditionRemarks: 'Both healthy', deliveryComments: 'Twin vaginal', deliveredBy: 'Dr. Iyer', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-12', babyCondition: 'Stable', babyOtherwiseReason: '', gender: 'Male', deliveryTime: '10:30', babyWeight: '2.6', apgarAt1Min: '7', apgarAt5Min: '9', dischargeDate: '2024-12-15', dischargeTime: '14:00', diagnosis: 'Twin vaginal delivery', complicationsFound: 'None', proceduresPerformed: 'Episiotomy', selectedLabTests: ['Hb', 'PCV'], selectedScans: ['USG growth info'], otherInvestigations: '', medicationsPrescribed: 'Supplements', dischargeConditionsInstructions: 'Normal care', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Iyer', followUp: '1 week' },
    { id: 'DEL-010', admissionDate: '2024-12-11', noOfChildren: 'Single', deliveryType: 'C-Section', csInstrumentalIndication: 'Breech', admissionTime: '13:00', tears: [], ebl: '450', episiotomy: 'No', suture: 'Vicryl', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Recovery normal', babyConditionRemarks: 'Healthy', deliveryComments: 'Elective CS', deliveredBy: 'Dr. Nair', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-11', babyCondition: 'Healthy', babyOtherwiseReason: '', gender: 'Female', deliveryTime: '13:45', babyWeight: '3.3', apgarAt1Min: '8', apgarAt5Min: '9', dischargeDate: '2024-12-15', dischargeTime: '09:00', diagnosis: 'Elective CS for breech', complicationsFound: 'None', proceduresPerformed: 'CS', selectedLabTests: ['Hb', 'RBS'], selectedScans: ['USG dating info'], otherInvestigations: '', medicationsPrescribed: 'Antibiotics', dischargeConditionsInstructions: 'Wound care', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Nair', followUp: '1 week' },
    { id: 'DEL-011', admissionDate: '2024-12-10', noOfChildren: 'Single', deliveryType: 'Normal', csInstrumentalIndication: '', admissionTime: '07:15', tears: [], ebl: '200', episiotomy: 'No', suture: '', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Excellent', babyConditionRemarks: 'Healthy', deliveryComments: 'Quick labor', deliveredBy: 'Dr. Das', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-10', babyCondition: 'Healthy', babyOtherwiseReason: '', gender: 'Male', deliveryTime: '08:00', babyWeight: '3.1', apgarAt1Min: '9', apgarAt5Min: '10', dischargeDate: '2024-12-12', dischargeTime: '10:00', diagnosis: 'Normal delivery', complicationsFound: 'None', proceduresPerformed: 'None', selectedLabTests: ['Hb'], selectedScans: ['USG dating info'], otherInvestigations: '', medicationsPrescribed: 'Iron', dischargeConditionsInstructions: 'Rest', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Das', followUp: '2 weeks' },
    { id: 'DEL-012', admissionDate: '2024-12-09', noOfChildren: 'Twin', deliveryType: 'C-Section', csInstrumentalIndication: 'Twin pregnancy', admissionTime: '15:40', tears: [], ebl: '550', episiotomy: 'No', suture: 'Vicryl', motherCondition: 'Satisfactory', otherwiseReason: '', motherConditionRemarks: 'Good', babyConditionRemarks: 'Both healthy', deliveryComments: 'Planned twin CS', deliveredBy: 'Dr. Bose', branch: 'Shri Rangadore Memorial Hospital', deliveryDate: '2024-12-09', babyCondition: 'Stable', babyOtherwiseReason: '', gender: 'Female', deliveryTime: '16:15', babyWeight: '2.7', apgarAt1Min: '7', apgarAt5Min: '9', dischargeDate: '2024-12-13', dischargeTime: '11:00', diagnosis: 'Twin CS', complicationsFound: 'None', proceduresPerformed: 'CS', selectedLabTests: ['Hb', 'PCV'], selectedScans: ['USG growth info'], otherInvestigations: '', medicationsPrescribed: 'Antibiotics', dischargeConditionsInstructions: 'Normal care', conditionAtDischarge: 'Stable', patientDisposition: 'Home', dischargedBy: 'Dr. Bose', followUp: '1 week' },
];
